wp:
  build: ./shapely
  links:
   - mysql
  environment:
   - WORDPRESS_DB_PASSWORD=O9923CBrRu
  ports:
   - "8080:80"
nginx:
  build: ./nginx
  links:
    - wp:wp
  ports:
    - "80:80"
    - "443:443"
mysql:
  build: ./db
  ports:
    - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=O9923CBrRu
   - MYSQL_DATABASE=wordpress