wp:
    build: ./shapely
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=O9923CBrRu
    ports:
     - "80:80"
     - "443:443"
mysql:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=O9923CBrRu
     - MYSQL_DATABASE=wordpress
     